export const divisions = [
  "CEO's OFFICE",
  "MAR COMMS",
  "CORPORATE SERVICES",
  "HUMAN RESOURCES",
  "MTED & DTS",
  "JOBS & SKILLS",
  "SBF GLOBAL",
  "STRATEGY & DEVELOPMENT",
];

export const departments = [
  "Advocacy & Actions",
  "Admin & FAC",
  "AMEA",
  "ASEAN",
  "China & North Asia",
  "Corporate Secretariat",
  "Digital Technology Services",
  "Finance",
  "Member Engagement",
  "Membership",
  "Engagement & Outreach",
  "FTA Edu & Outreach",
  "Infrastructure",
  "Int'l Policy & Engagement",
  "JDP",
  "Plans & Operations",
  "Policy and Planning",
  "Research & Publishing",
  "SBF Business Institute",
  "SGUJ",
  "SGUT & SGUP",
  "Strategic Relations",
  "USA, EU & Oceania",
];